import "./globals.css";

// // step 1
// import localFont from "@next/font/local";

// // step 2
// const myLocalFont = localFont({
//   src: "../public/fonts/font1.woff",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
